import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./components/Providers";
import { VideoProvider } from "@/app/components/ContextProvider";

// // Load Geist Sans
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"], // Choose only needed weights
//   preload: false, // Avoid build-time fetch issues
// });

// // Load Geist Mono
// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
//   weight: ["400", "500", "700"], // Choose only needed weights
//   preload: false, // Avoid build-time fetch issues
// });

export const metadata: Metadata = {
  title: "Video App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <VideoProvider>
        <Providers>{children}</Providers>
        </VideoProvider>
      </body>
    </html>
  );
}
